server:
  port: 5020
spring:
  servlet:
    multipart:
      max-file-size: 10MB
  main:
    allow-bean-definition-overriding: true
  redis:
    database: 0
    host: 81.70.169.127
    port: 6379
    password: 123
  devtools:
    restart:
      enabled: true
  application:
    name: iblog-attach
  cloud:
    nacos:
      discovery:
        server-addr: 81.70.169.127:8848
#        ip: 82.156.214.247
    sentinel:
      transport:
        dashboard: 81.70.169.127:8858
  datasource:
    url: jdbc:mysql://82.156.214.247:3306/eblog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true
# Feign对Sentinel的支持
feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 600000

# 图片上传下载
web:
  upload-path: ${user.dir}/img

# 文件服务器
fileServer: ${spring.application.name}/images
resourcePath: file:${web.upload-path}/