server:
  port: 5000
spring:
  servlet:
    multipart:
      max-file-size: 10MB
  devtools:
    restart:
      enabled: true
  application:
    name: iblog-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 81.70.169.127:8848
    sentinel:
      transport:
        dashboard: 81.70.169.127:8858
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            # allowedOriginPatterns: "*"           #注意这个设置只对 spring boot 2.4+ 有效，低版本 使用  allowedOrigins: "*" 属性
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true